### ISSUE TITLE
iOS > Paths do not reconcile

### ISSUE THREAD

**Issue by michaelpeterlee** [apache/cordova-plugin-file#287]
cordova 8.1.0
cordova-plugin-file 6.0.1

Paths not reconcile for any Cordova File iOS path in the cordova.file object, below.

![image](https://user-images.githubusercontent.com/19398181/50868606-28081d80-1415-11e9-9916-2ab4d45e6125.png)

Re: 

```  
_oFileSystem = await window.requestFileSystem(1, 0); // Pseudo

_oFileSystem.root.getFile('305282.mp4',{create: true,exclusive:false},

  function success(oFileEntry) {
   console.log('file/_cordova.js.open()',oFileEntry);
  },
  function fail(oError) {
  }

);
``` 

When we create a file it returns:

![image](https://user-images.githubusercontent.com/19398181/50868618-335b4900-1415-11e9-9a3c-5310ec1cb576.png)

Q. Can someone please advise the correct directory we should be storing/referencing for private non-sharable files?

**Comment by NetZAL** [comment]
hello, when I console.log(cordova.file), all is null, do you know why？ all the path is null

**Comment by janpio** [comment]
What do you mean by "Paths not reconcile"?

**Comment by michaelpeterlee** [comment]
Hi,

The above screenshot paths are different, they do not reconcile, they should reconcile.
We transform to resolve the correct path by overriding path requests, we should not have to do that.

Mike

**Comment by janpio** [comment]
Could you please point out the paths that "should reconcile". I see a list of all the available "locations", and a `FileEntry` with a `nativeURL` that seems to be in the `applicationStorageDirectory`.

**Comment by michaelpeterlee** [comment]
Referencing the screenshots: `nativeURL` should refer `documentsDirectory`, however it refers `*/files` instead.

**Comment by breautek** [comment]
This isn't a bug.

> await window.requestFileSystem

Using `requestFileSystem` in `PERSISTENT` mode on iOS is mapped `Library/files`. This is an implementation detail and thus isn't documented. I do not know the historical reason why this was chosen, but changing this would be a breaking change and I don't believe that is necessary. My best guess is Cordova was trying to implement the File API according to the W3C spec, and needed to use a storage folder that was unlikely to conflict with the other constants.

If you want the documents directory, then use `window.resolveLocalFileSystemURL(cordova.file.documentsDirectory, successCallback, errorCallback)` instead.

> Can someone please advise the correct directory we should be storing/referencing for private non-sharable files?

Everything inside the application directory (e.g: `file:///var/mobile/Containers/Data/Application/<GUID>/` is private to the app. All non-external constants in `cordova.file` is also private to the app.

In fact, there is no publicly accessible directories on iOS. That concept doesn't exists unlike other platforms, which is why all the `external*` constants are null on iOS. Sharing files like audio or images can only be done via other APIs not related to the filesystem.

More information on this is documented at https://github.com/apache/cordova-plugin-file#ios-file-system-layout
