### ISSUE TITLE
Gallery path

### ISSUE THREAD

**Issue by ayubUOL** [apache/cordova-plugin-file#430]
# Feature Request
Hi everyone, I'm working on some app in which I need to download image and save it to gallery but unfortunately I'm unable to save image to gallery because I don't know how to make path to gallery so that I can save the image there. 

# Motivation Behind Feature

I tried File transfer plugin, base64ToGallery plugin and CanvasToGallery plugin but they are deprecated or it didn't work. I searched on internet to find some proper explanation for this but didn't find any. 

It's my humble request to please consider this request because there is no proper answer out there for this gallery path problem.

**Comment by iljaverba00** [comment]
Hi, you have a solution by this ?

**Comment by breautek** [comment]
For iOS I don't think this is possible due to the iOS filesystem sandbox.

For android, the standard directory is the `DCIM` folder, which can be reachable regardless if the sdcard is emulated or not via `cordova.file.externalRootDirectory + "DCIM/"`

However if that folder is **actually** used by your installed gallery is another question. I'm also not sure if this directory is writable with scoped storage rules.

Further support questions like this belongs more on our [Discussions](https://github.com/apache/cordova/discussions) board.
