### ISSUE TITLE
Doesn't work with React

### ISSUE THREAD

**Issue by ollydixon** [apache/cordova-plugin-file#437]
The project has angular speific functions and calls.
Cannot use this via React, very annoiyng.

**Comment by breautek** [comment]
Are you sure?

I use this plugin very extensively in my react based projects so I'm pretty certain this library does not contain any angular specific functions (or any framework for that matter). Please do point for us where exactly the angular function calls are being made from within this plugin, it would help us a lot.

**Comment by ollydixon** [comment]
@breautek 100% certain just spent the last few hours installing it into a blank project and trying to get it too run. I can also see what when it's installed the angular calls are there.

Thanks for closing the issue instantly.

**Comment by ollydixon** [comment]
@breautek if you look at the index.js you can the calls to angular.

**Comment by breautek** [comment]
> @breautek if you look at the index.js you can the calls to angular.

This plugin doesn't have an `index.js` file.

**Comment by ollydixon** [comment]
@breautek mate all node_modules have index.js files.
I'm using the instructions here ```https://ionicframework.com/docs/v3/native/file/```

**Comment by ollydixon** [comment]
And the instrutions here: https://ionicframework.com/docs/native/file

**Comment by ollydixon** [comment]
```
npm install cordova-plugin-file
npm install @ionic-native/file
ionic cap sync
```

Installs a version with Angular calls you can see from the JS on the index.

**Comment by breautek** [comment]
> @breautek mate all node_modules have index.js files.
> I'm using the instructions here `https://ionicframework.com/docs/v3/native/file/`

Cordova plugins are not traditional node_modules. Plugins don't always have single entry point, and furthermore NPM doesn't run on devices. The only way NPM is involved in cordova plugins is that NPM is used as a distribution method, but the `package.json` `main` field does not apply.

Also Ionic is a framework that uses but is independent from Cordova. So what it sounds like is something in the Ionic's code base that is using Angular, which makes a little more sense since Ionic was originally built as an Angular framework for Cordova, if I recall correctly. In which case, you'll have to communicate with the Ionic team.

Again, i'm pretty confident there are no angular calls being made from this code base. If I'm wrong, please do point me to the file and line numbers in https://github.com/apache/cordova-plugin-file/tree/master/www and I'll reopen this issue.
