### ISSUE TITLE
How to retrieve files from hidden folder in Android

### ISSUE THREAD

**Issue by shoaib07860** [apache/cordova-plugin-file#514]
Is there way to read media files from hidden folder?
I am able to access folders using method window.resolveLocalFileSystemURL and can read files from specific folder using readEntries.
But unable to read files from hidden folder starting with '.'

May be this functionality isn't available yet.
Is it possible to achieve it with current version of plugin.

Regards

**Comment by breautek** [comment]
If your app process have permission to read a folder, you should be able to access it just like any other normal directory, however, many directories outside of your application directory is not readable by the application user that your app runs under, and may return the "File does not exist" error (even if the file does actually exist, but your app doesn't have permission to know about it).

Closing because there is insufficient information. If you believe there is a bug, please open a new issue with the issue formed filled out.
