### ISSUE TITLE
iOS Source code shows many deprecations

### ISSUE THREAD

**Issue by sreekanthrad** [apache/cordova-plugin-file#533]
# Bug Report

### What is expected to happen?
Deprecation warnings should be removed as it can affect the Appstore submission.

### What does actually happen?
Different classes have multiple deprecation warnings.

### Environment, Platform, Device
iOS platform

### Version information

cordova-ios 6.x
cordova-plugin-file 7.x

***Please consider with high priority.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Often using, or having deprecated code in the codebase is necessary in order to remain backwards compatible with older iOS versions. Therefore we cannot just blanket sweep all deprecations and refactor them to whatever what the replacements are. At the time of release of cordova-ios@6, it was decided to support iOS 11 and later. Nowadays, iOS 11 probably is pretty ancient and support could **probably** be dropped, but it would require rolling out new majors.

In my experience, which includes providing support for the Apache Cordova community...  Apple doesn't block apps if they are using deprecated code, and if they have the intention to do so for specific deprecations, they will announce it (e.g. the UIWebView deprecation).

So if Apple is blocking one of your apps from submission due to a deprecation code being used, it would be useful to know which deprecations they are referencing.

**Comment by breautek** [comment]
Closing as stale/no response.
