### ISSUE TITLE
FileUtils.java:1268: error: lambda expressions are not supported in -source 7

### ISSUE THREAD

**Issue by shamsundhar** [apache/cordova-plugin-file#539]
# Bug Report

## Problem
cordova build targetting android 11 failing

### What is expected to happen?
Cordova build should work fine

### What does actually happen?
cordova build is failing when targetting for android 11

### Command or Code

cordova plugin add cordova-plugin-file@7.0.0
cordova plugin add cordova-plugin-file-transfer
cordova build android

### Environment, Platform, Device

macOS

### Version information
Cordova -11.0.0,
Cordova-plugin-file@7.0.0
cordova android 11.0.0
 java version is 11.0.16.1 and JAVA_HOME value is "/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home"
Mac OS, Android Studio.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Please include your java version, or ensure that you're `JAVA_HOME` & `PATH` leads to a JDK 11 installation / binaries.

**Comment by shamsundhar** [comment]
Hi breautek, my java version is 11.0.16.1 and JAVA_HOME value is "/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home"

**Comment by breautek** [comment]
Thank you... that looks alright to me.

`-source 7`

This seems like something is tacking on (and overriding [cordova's configuration](https://github.com/apache/cordova-android/blob/954d3e0e7542356e6ea995ddc75dcb1db8bb36cc/templates/project/app/build.gradle#L249)).

The `-source` flag sets the `sourceCompatibility` to a specific Java level, and 7 is not compatible because lambda expressions was introduced in Java 8.

I've confirmed that Cordova will build a standard hello world application with the file plugin. So it's likely an environment variable, user-level setting, third-party cordova plugin or a user-level gradle config that is overriding the `sourceCompatibility` option.

**Comment by breautek** [comment]
Closing as stale
