### ISSUE TITLE
Saving image [base64] to app folder or external folder 

### ISSUE THREAD

**Issue by midomario** [apache/cordova-plugin-file#546]
Hello i want to save an image created with domtoimage library its downloadable on the web but is not on a device or emulator.

* I can't use capacitor because one of the packages i need  is outdated ..... 
* domtoimage : 
Save and download a compressed JPEG image 
Or
Get a PNG image blob

---

The goal here is to :
1- create a to-do list & show it as ion-list [DONE]
2-  then use dom-to-image  to render it as an image [DONE]
3- share it using Social Sharing plugin[.....]

**Comment by breautek** [comment]
So what's the problem?

**Comment by breautek** [comment]
That's still not describing the problem with this plugin. It would be better if you followed the issue template instead of erasing it when creating the issue, so that we can get more information regarding the issue.

If you're asking for support on how to save an image, then I would refer you to the [Samples](https://github.com/apache/cordova-plugin-file#append-a-file-using-alternative-methods-). There is also a table of constants/filepaths available [here](https://github.com/apache/cordova-plugin-file#android-file-system-layout). If you have further questions, a better place to ask is on our [Discussions](https://github.com/apache/cordova/discussions).

For support for the share plugin, as that is a third party plugin, it will be better to ask the plugin maintainers.

I'm closing this as there doesn't appear to be describing a bug with the file plugin. If there is a bug, I'd suggest creating a new issue with the issue form filled out, so that we can get a better understanding of the context in which the bug occurs.
