### ISSUE TITLE
Ios persistent data 

### ISSUE THREAD

**Issue by PAVANDEVA** [apache/cordova-plugin-file#548]
i want to persist data even after deleting the app . i could able to achieve it in android but in ios, if the application is deleted and relaunched i am not able the fetch data. 

in android i am using the below method

  window.requestFileSystem(LocalFileSystem.PERSISTENT, 0, function(fs) {
      fs.root.getDirectory(
        "******",
        { create: true },
        fetchExistingFile
      );
    });

 const fetchExistingFile = (fileEntry) => {

   fileEntry.getFile("#####.txt", { create: false }, readFile);
    };
 const readFile = (fileEntry) => {
      fileEntry.file((file) => {
        var reader = new FileReader();
         reader.onloadend =  function() {
  
          sendData(reader.result)
        };
        reader.readAsText(file);
      });
    };

Note: above code working in android.

is there anyway i could achieve this in ios .

your help is most appreciated.Thank you.

**Comment by breautek** [comment]
You need to use a directory that is "synced" to the cloud, such as `cordova.file.syncedDataDirectory`. Note that this constant only exists for iOS. Android does not have a `syncedDataDirectory` equivalent. Whether or not data survives app deletes depends on user device settings. You can't actually rely on this behaviour.

Android doesn't have an equivalent, however some devices will retains an app's data directory for a period of time after uninstall, or sometimes the user can sync their phone to the cloud which includes app data directories, that will be recovered on reinstall, but there is no special directory that is synced to the cloud like iOS has. In other words, you cannot guarantee that your data will survive app uninstalls.

I'm closing this issue because this doesn't describe a bug. For support style questions, I suggest asking on our [Discussions](https://github.com/apache/cordova/discussions) board.
