### ISSUE TITLE
Support for Android api 33

### ISSUE THREAD

**Issue by ohtanzcom** [apache/cordova-plugin-file#561]
# Feature Request

## Motivation Behind Feature

READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE used in FileUtils.java from API 33 are no longer available.
Instead, fine-grained permission controls such as READ_MEDIA_IMAGES are required.

![2023-03-01 01_55_11-Clipboard](https://user-images.githubusercontent.com/69287535/221922899-c5c8b1b1-c1b0-463c-b58e-869e711bfb89.png)

If there are no comments in the screenshot section, shared storage cannot be accessed even if MANAGE_EXTERNAL_STORAGE permission is granted.

**Comment by MauriceFrank** [comment]
Thanks for mentioning it ! 
We are also depending on the new permission READ_MEDIA_IMAGES for Android 13. Without plugin changes, file transactions with this plugin fail with error "encoding error code 20" which is the missing permission.

**Comment by MauriceFrank** [comment]
@breautek Thank you for your answer and suggestions !

I have also tried using the cordova-android-permissions plugin, to request the READ_MEDIA_IMAGES directly before using the file plugin. Unfortunately without success. So I guess the permission request change is definately needed within the plugin itself.

**Comment by ohtanzcom** [comment]
@MauriceFrank

I have done the following work to resolve this.

- Comment out everything about READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE
- Pre-request permissions for READ_MEDIA_IMAGES, READ_MEDIA_VIDEO, and READ_MEDIA_AUDIO with the following plugin

https://github.com/dpa99c/cordova-diagnostic-plugin

Use the plugin "requestRuntimePermission".

**Comment by MauriceFrank** [comment]
Hey there,

are there any news regarding Android 13 support ? 

Best regards,
Maurice

**Comment by MauriceFrank** [comment]
> @MauriceFrank
> 
> I have done the following work to resolve this.
> 
> * Comment out everything about READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE
> * Pre-request permissions for READ_MEDIA_IMAGES, READ_MEDIA_VIDEO, and READ_MEDIA_AUDIO with the following plugin
> 
> https://github.com/dpa99c/cordova-diagnostic-plugin
> 
> Use the plugin "requestRuntimePermission".

Thanks for your suggestion! I Might try that, although I would prefer not using any separate and additional plugins and still hope for updates within this file-plugin :/

**Comment by MauriceFrank** [comment]
> > shared storage cannot be accessed even if MANAGE_EXTERNAL_STORAGE permission is granted.
> 
> This could be a bug in the android platform, as `MANAGE_EXTERNAL_STORAGE` is suppose to provide [All Files Access](https://developer.android.com/about/versions/11/privacy/storage#all-files-access). So if this is not providing you access, a bug maybe should be raised with Android, if not already.
> 
> However, `MANAGE_EXTERNAL_STORAGE` external access requires justification to use if you intend to deploy through the google play store, so unless if you absolutely have a need for the permission (such as a File manager kind of app), you should be using the granular permissions.
> 
> I've added this to the 8.x milestone as it will require a breaking change (we need the cordova-android@12 which is currently in development for SDK 33.
> 
> > Are there any known workarounds / alternatives ?
> 
> I don't think there is an easy way. At minimum, you'll need to fork and get your hands dirty to monkey patch in requesting the appropriate permissions.
> 
> A workaround would require:
> 
> 1. cordova-android@11 (as it has API 31+ support)
> 2. `android-buildToolsVersion` preference set to `33.0.0` (or the latest patch available, ideally). Android SDK Manager also needs to be used to install the build tools version.
> 3. `android-compileSdkVesion` set to `33`
> 4. `android-targetSdkVersion` set to `33`
> 5. Potentially updates to additional androidx dependencies if any of them has a max sdk version set that is less than `33`
> 6. Update to https://github.com/apache/cordova-plugin-file/blob/b32be30e4bd012f9d9568a9cc11926b2ad6c14f7/src/android/FileUtils.java#L106
>     to add the new permissions. Note that `READ_EXTERNAL_STORAGE` I think is still required if your app can run on devices pre-API 33. `WRITE_EXTERNAL_STORAGE` I believe is still required if your app can run on devices pre-API 29.
> 7. https://github.com/apache/cordova-plugin-file/blob/b32be30e4bd012f9d9568a9cc11926b2ad6c14f7/src/android/FileUtils.java#L580
>     will need to be updated to use the one of the new read permissions if the API is >= 33, and falback to `READ_EXTERNAL_STORAGE` otherwise.
> 8. This list is not exhaustive, there could be things missing, this is just a initial first glance analysis.


Thanks! Your suggestions work - at least the method "file.listDir()" I had security errors with.
I actually tried the changes first with READ_MEDIA_IMAGES and the method "file.listDir()" did not throw any security errors anymore, while accessing external storage directories like the "Pictures" folder and entries within it.


However, there are 3 new READ-Permissiosn for Android 13+ needed, therefore we would need to request all 3.
I created a Pull-Request if anyone is interested in the change or needs media-file access (read) on Android 13, located in the external storage such as the Gallery:

https://github.com/apache/cordova-plugin-file/pull/566

However, this will automatically request all 3 permissions(images,video and audio). If the file-plugin should only request the needed permission for the specific read-request, the plugin has to be changed in a more extensive way.

**Comment by breautek** [comment]
> However, this will automatically request all 3 permissions(images,video and audio). If the file-plugin should only request the needed permission for the specific read-request, the plugin has to be changed in a more extensive way.

It's not ideal but I'm not sure there is a way around it coming from a generic filesystem plugin standpoint. In order to be more specific, we'd probably need some kind of contextual API rather than working with a URI which could be anything (regardless of extension).

With all these privacy-centric changes being introduced since API 30, it's starting to feel less sense for the filesystem API to handle the external storage, for two reasons:

A) It's not even recommended to use the File API for external storage, they have a `MediaStore` interface for accessing these files instead.
B) There is no File API bridge on API 29, so using external storage is completely broken on API 29 devices. The File API bridge was only introduced in API 30. On API 29 devices, the only way to access the external filesystem files is through the `MediaStore` interface.

But https://github.com/apache/cordova-plugin-file/pull/566 is definitely would be an okay stopgap for cordova-android@12.

**Comment by MauriceFrank** [comment]
> > However, this will automatically request all 3 permissions(images,video and audio). If the file-plugin should only request the needed permission for the specific read-request, the plugin has to be changed in a more extensive way.
> 
> It's not ideal but I'm not sure there is a way around it coming from a generic filesystem plugin standpoint. In order to be more specific, we'd probably need some kind of contextual API rather than working with a URI which could be anything (regardless of extension).
> 
> With all these privacy-centric changes being introduced since API 30, it's starting to feel less sense for the filesystem API to handle the external storage, for two reasons:
> 
> A) It's not even recommended to use the File API for external storage, they have a `MediaStore` interface for accessing these files instead. B) There is no File API bridge on API 29, so using external storage is completely broken on API 29 devices. The File API bridge was only introduced in API 30. On API 29 devices, the only way to access the external filesystem files is through the `MediaStore` interface.
> 
> But #566 is definitely would be an okay stopgap for cordova-android@12.

Thanks for the fast response and check of the PR! I agree, it is definitely not ideal - In my case it will do the job, but I am also searching for a better solution, such as a cordova-plugin, which is using the MediaStore API.
Are there any recommended cordova-plugins known, which are using the MediaStore API ? So far I did not find any "good" ones which are completely useable.

**Comment by LucasBourgeois** [comment]
Any news about this? 
cordova-android@12 is released with support of api 33 and Google mandatory api 33 target time limit is tomorrow.

**Comment by adeel399** [comment]
My whole app based on camera, video and file plugin to make local gallery nothing is working on android 13 with target sdk 33 

Please any solution what change i should do .. already added permission in android manifest file with maxsdkversion 32 .. help needed!!

**Comment by willPHPwork** [comment]
> My whole app based on camera, video and file plugin to make local gallery nothing is working on android 13 with target sdk 33
> 
> Please any solution what change i should do .. already added permission in android manifest file with maxsdkversion 32 .. help needed!!

You find a solution?

**Comment by andresmq** [comment]
Hi all,

I tried with Cordova 12 (file plugin version 8.0.0) writing a file to the well-known folder cordova.file.externalRootDirectory/Download but it doesn't work (error code = 2).

Android doesn't require any extra permission for that folder I think the method FileUtils.needPermission(...) should be fixed to take into account that path.

Regards

**Comment by breautek** [comment]
> Any news about this? cordova-android@12 is released with support of api 33 and Google mandatory api 33 target time limit is tomorrow.
> 
> Edit: with further research if just found that it was release in 8.0: #566
> 
> This issue is maybe to close and resolve ?

Indeed, I guess the PR missed this issue link.

> I tried with Cordova 12 (file plugin version 8.0.0) writing a file to the well-known folder cordova.file.externalRootDirectory/Download but it doesn't work (error code = 2).

Error code 2 is a SECURITY_ERROR, which is generally related to permissions.

This code I believe is always thrown on API 29 devices because Scoped Storage does not have Direct File Access.
I believe this code is also thrown if you're attempting to write to a file that your app does not own, which is also prohibited under scoped storage rules.

In either case, you'll need to a plugin that interfaces with android's Media Store API instead of a file-based plugin such as this one. More details on this [here](https://github.com/apache/cordova-plugin-file#androids-external-storage-quirks) along with a NPM search link for media store plugins.

Generally speaking, if your interacting with external storage (and thus scoped storage system), migrating to a media store plugin is going to be desirable.

Closing as fixed by #566

**Comment by adeel399** [comment]
> > My whole app based on camera, video and file plugin to make local gallery nothing is working on android 13 with target sdk 33
> > 
> > Please any solution what change i should do .. already added permission in android manifest file with maxsdkversion 32 .. help needed!!
> 
> You find a solution? 

Not yet

**Comment by andresmq** [comment]
> Error code 2 is a SECURITY_ERROR, which is generally related to permissions.
> 
> This code I believe is always thrown on API 29 devices because Scoped Storage does not have Direct File Access. I believe this code is also thrown if you're attempting to write to a file that your app does not own, which is also prohibited under scoped storage rules.
> 
> In either case, you'll need to a plugin that interfaces with android's Media Store API instead of a file-based plugin such as this one. More details on this [here](https://github.com/apache/cordova-plugin-file#androids-external-storage-quirks) along with a NPM search link for media store plugins.
> 
> Generally speaking, if your interacting with external storage (and thus scoped storage system), migrating to a media store plugin is going to be desirable.
> 
> Closing as fixed by #566

Thanks @breautek for your reply. 

There is something I don't yet understand:
According to [Media store](https://developer.android.com/training/data-storage/shared/media#media_store) the **Downloaded files** collection contain the files that are stored in the _Download/_ directory and according to [Access your own media files](https://developer.android.com/training/data-storage/shared/media#storage-permission-not-always-needed) you don't need storage-related permissions to access and modify the files in that collection. Moreover, I forked the branch 7.0.0 and patched the **FileUtils** class to return false when testing if permissions are needed when accessing the _Download/_ directory and could manage to create files into that folder without any error.

There is something I'm missing or the plugin should be patched to take into account the Download/ folder?

Thanks in advance!

**Comment by breautek** [comment]
> There is something I'm missing or the plugin should be patched to take into account the Download/ folder?

The rules are different depending on the API level of the device.

### API Level 24-28

`WRITE_EXTERNAL_STORAGE` is required for all external storage paths **except** for your application's external data/cache directory. The `Download/` folder is not application specific, so `WRITE_EXTERNAL_STORAGE` permission will be required.

This is "pre-scoped storage" rules.

### API 29 Devices specifically

Starting with API 29, Scoped Storage rules was introduced. With scoped storage, `WRITE_EXTERNAL_STORAGE` became obsolete, because with scoped storage you no longer need permission to write to external storage. So requesting the `WRITE_EXTERNAL_STORAGE` doesn't grant any additional permissions itself, **however** it does still implicitly grant `READ_EXTERNAL_STORAGE` which is why Cordova still uses for API 24-32.

On API 29 specifically, direct filesystem access was disabled, this means you cannot access the external storage via File APIs, which this plugin uses. This is one of the reasons why a media store or SAF plugin becomes necessary.

### API 30-32

Android fixed the limitation of disabling filesystem access to external storage, so we can now read/write to external storage without any explicit permissions (either read or write) using the File plugin API. As a result this plugin will work again, but direct filesystem access has limitations:

1. You can only read/write to files that you (your application) has created.
2. You cannot write to any file that isn't owned by your application.
3. With the `READ_EXTERNAL_STORAGE` permission, you may read **media** files owned by other applications. Media files are limited to: audio, images, and video.
4. Not all paths inside external storage medium is writable, so if you were writing to custom folders before, they may still be inaccessible under scoped storage.

If any of these limitations affects you, then a media store / SAF plugin will be required, as they contain APIs to gain temporary permission to a specific file not owned by your app, for both reading and writing.

Also note that discovery of files is also limited under scoped storage (e.g. listing a directory).

### API 33+

Not much as changed in API 33, except for that `READ_EXTERNAL_STORAGE` is now an auto reject and instead they have 3 new permissions:

- `READ_MEDIA_AUDIO`
- `READ_MEDIA_VIDEO`
- `READ_MEDIA_IMAGES`

Keen eyes will observe that there are only read permissions for the types of media that was supported for reading previously. If you need to read other kinds of files owned by other apps, Media Store / SAF plugin is required.

This plugin will request all 3 of those permissions on API 33+ via https://github.com/apache/cordova-plugin-file/pull/566

### Moving forward

Unless if you only support API 30+, a MediaStore/SAF plugin will be necessary for API 29 support. The native Media Store API is not "File API" friendly. It would be incredibly awkward to represent files as directories and files with a traditional File API as this plugin implements, when the underlying storage mechanism is through the MediaStore, because the MediaStore is **not** a File API. So I don't foresee the File plugin turning into a SAF plugin. The file plugin is still useful for managing files inside the internal storage (e.g. the apps private data files).

Moving to my own opinions, (e.g. not sure if Apache will agree with this take)... The file plugin can be incredibly simplified by removing support for external storage and just represent file paths as Files, and if it has permission to read/write to it, then it will do it's thing. The file plugin main responsibility should be for managing the app's data files, but not necessary shared files, which is where a SAF plugin will come in to fill that gap. Some other Apache plugins still depends on external storage support via File plugin so those will have to be changed/corrected first, but this is the direction that I'm kinda pushing for.

Do note that the native MediaStore concept has been around since API 1... It was always the recommended mechanism for sharing files/content in Android, it was just easier, especially at a generic level to manage files as files. Today, it's no longer easier to manage shared content as files.

So generally speaking, if you're operating with the external file system, I'd highly recommend to migrate to a SAF / MediaStore plugin. It will likely provide better stability moving forward.

Hope this helps clear things up.

**Comment by andresmq** [comment]
@breautek thank you very much for your detailed explanation. 
Regards

**Comment by willPHPwork** [comment]
> @breautek thank you very much for your detailed explanation. Regards

You find a solution? I'm confused on this part "You can only read/write to files that you (your application) has created." as I am trying to create new images to the download folder and I still get error code 2. However, this plugin works though: https://www.npmjs.com/package/cordova-plugin-pvt-save-image-gallery but the images are downloaded to the pictures folder. cordova-plugin-file doesn't work for download or pictures folder.

**Comment by andresmq** [comment]
@willPHPwork Yes, I could manage it for our use cases.

I patched the plugin to not request permission for the _"getDirectory"_ action when the path is the `externalRootDirectory/Download/` folder. **That works for API level != 29**, for the specific case of 29 we store the files in an application's specific folder (`externalApplicationStorageDirectory/Download`).
