### ISSUE TITLE
Wildcard

### ISSUE THREAD

**Issue by Covarians** [apache/cordova-plugin-file#567]
Is there a way to use filename with wild card in the getFile function ?

Thanks for your help.
FG

**Comment by breautek** [comment]
No, the file plugin nor the underlying native API doesn't understand wildcard/file expansion operations.

If you have a glob API, you could list the files and apply the glob against the file API. Recursive scanning on mobile filesystems tends to be really slow however, and you'll need to explicitly list each subdirectory manually if you want a recursive search.

Closing because this kind of feature would be out of scope of this plugin.
