### ISSUE TITLE
.toURL() for android not working on Android in an Ionic Cordova app

### ISSUE THREAD

**Issue by dinitri** [apache/cordova-plugin-file#634]
# Bug Report

## Problem
Cannot load image in <img src=""/>  element since cordova plugin file update
### What is expected to happen?

Be able to update cordova-plugin-file in an Ionic Cordova app and load in image in img or ion-img components

### What does actually happen?
I updated the cordova-plugin-file from version 6 to 8 in my Ionic Cordova app, I am encoutering a file not found issue with the URL generated with FileEntry.toURL() method.

With `cordova-plugin-file@6.0.2` everything was working fine on android. The `toURL` method was returning `file:///data/user/0/com.package.name/filename.jpg` , but now with `cordova-plugin-file@8` the `FileEntry.toURL()` is returning `https://localhost/__cdvfile_files__/filename.jpg`. I guess this change is due to the introduction of a new `Entry.js` file under the `/android` directory. I thought it would not cause any issue but the generated url `https://localhost/__cdvfile_files__/filename.jpg` does not work when it is loaded in the `<img src="" />` tag.

In version 6, I am using the `.toURL()` which returns the the nativeURL `file:///data/user/0/com.package.name/filename.jpg`
and then I convert this nativeURL with `window.Ionic.Webview.convertFileSrc(file:///data/user/0/com.package.name/filename.jpg)`
which gives the following url: `https://localhost/__app_file__/data/user/0/com.package.name/files/filename.jpg` and this url worksin an `<img src="" />` tag

I'm not getting why `https://localhost/__app_file__/data/user/0/com.package.name/files/filename.jpg` is working and not
`https://localhost/__cdvfile_files__/filename.jpg` as generated with the toURL method in version 8.

I have a work around by using the `FileEntry.nativeURL` attribute and convert it with the convertFileSrc method but I don't know if it's the best way to solve this issue.

Any ideas ?

## Information

cordova-android: 13.0.0
Target API 34

### Environment, Platform, Device

Android
Cordova

### Version information

cordova-android: 13.0.0
Target API 34

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
The default cordova webview parses the format `https://localhost/__cdvfile_files__/filename.jpg`.

It seems like the ionic webview does something slightly different.

Historically `toURL` was meant to produce DOM-usable URLs which broke once Cordova stopped using the `file://` protocol to host local app content and instead using schemes. Which is why toURL changed to produce `http(s)://` urls so they get passed through the native asset loader and are not blocked by CORs.

If the `AndroidInsecureFileModeEnabled` preference is enabled, the file plugin assumes that the webview is still operating in the older file protocol mode and `toURL` should continue to return `file://` paths similar to v6 behaviour. But I don't know if the ionic webview responds to this preference or not. Alternatively you can continue to use `nativeURL` property which in most cases will be a `file://` path. On android it may also be a `content://` path depending on the source of the content.

I don't consider this a bug with the file plugin. This will work as expected with the default webview that Cordova provides. It will be on the Ionic webview to parse/adapt the paths. Note that Cordova plugins can define custom path handlers which the file plugin does [here](https://github.com/apache/cordova-plugin-file/blob/master/src/android/FileUtils.java#L1242), so if the ionic webview when they build their [WebViewAssetLoader](https://developer.android.com/reference/androidx/webkit/WebViewAssetLoader), they could include plugin path handlers so that the webview can fully support the file plugin.
